In [126]:
import pandas as pd 
df1=pd.read_csv("C:\\Users\\Sravani\\Desktop\\us_customer_data.csv")
df2=pd.read_csv("C:\\Users\Sravani\\Desktop\\transaction_data.csv")
df=pd.merge(df1,df2, on="customer_id")

In [127]:
df

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,619-723-4258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8,2652.57,2025-04-19 14:46:00,Home,Credit Card,New York
1,4,Kimberly Price,jessicaknight@example.com,423-222-9779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427,1787.09,2025-04-28 04:34:07,Beauty,PayPal,Chicago
2,5,Matthew Phillips,qwilliams@example.com,220-763-3522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452,1983.52,2025-02-03 14:59:13,Sports,PayPal,Online
3,7,Louis Miller,patriciaelliott@example.org,198-862-7105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,470,3241.66,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles
4,7,Louis Miller,patriciaelliott@example.org,198-862-7105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,857,697.57,2025-06-13 12:03:42,Beauty,Debit Card,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Deanna Johnson,ycook@example.org,576-320-4824,"601 Contreras Forges, Michaelfurt, KY 30733",01-11-2023,Silver,532,759.38,2025-03-14 16:56:22,Home,PayPal,New York
996,995,Deanna Johnson,ycook@example.org,576-320-4824,"601 Contreras Forges, Michaelfurt, KY 30733",01-11-2023,Silver,617,821.18,2025-01-23 07:39:19,Electronics,Debit Card,Miami
997,997,Jodi Simpson,eric24@example.org,483-625-2940,"2876 Tucker Road Suite 947, North Tommyborough...",18-04-2024,Bronze,45,480.64,2025-01-06 08:27:59,Home,Credit Card,Los Angeles
998,998,Crystal Brown,pshaffer@example.net,390-747-3088,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",30-08-2024,Bronze,304,73.71,2025-01-27 05:33:22,Home,Debit Card,Chicago
999,998,Crystal Brown,pshaffer@example.net,390-747-3088,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",30-08-2024,Bronze,886,NaN,2025-03-16 15:42:17,Beauty,Debit Card,Online

In [128]:
df1= df.drop_duplicates()
df2=df.drop_duplicates()

In [129]:
#fixing the names column
df1['name'] = df1['name'].str.title()
df1['name'] = df1['name'].fillna('unknown')

In [130]:
#dealing with emails column 
df1['email'] = df1['email'].fillna(df1['name'].str.replace(' ','').str.lower()+'@example.com')

In [131]:
#fixing the amount with mean
df2['amount'] = df2['amount'].fillna(df2['amount'].mean())

In [132]:
#extrcating country code from address
df1['countrycode']= df1['address'].str[-8:-6]
cc=df1['countrycode'].unique()
cc

array(['AE', 'CA', 'OR', 'CT', 'WA', 'IL', 'AA', 'FM', 'AP', 'RI', 'PW',
       'FL', 'MT', 'IA', 'VA', 'NC', 'CO', 'SD', 'MP', 'AL', 'MH', 'MD',
       'NV', 'WI', 'HI', 'GU', 'MA', 'ID', 'KS', 'IN', 'DE', 'KY', 'AS',
       'TN', 'MO', 'OH', 'MS', 'OK', 'NE', 'NY', 'DC', 'ME', 'AZ', 'GA',
       'WY', 'VI', 'SC', 'PA', 'ND', 'TX', 'AR', 'NH', 'PR', 'WV', 'NJ',
       'NM', 'VT', 'AK', 'UT', 'MI', 'LA', 'MN'], dtype=object)

In [133]:
#convert datatype of phone column  to string 
df1['phone'] = df1['phone'].astype(str)
df1['phone'] = df1['phone'].str.replace('-','')
#dealing with the phone number 
def fix_value(df1):
    p=len(df1['phone'])
    for i in range(p):
        if len(df1['phone'][i])>10 or len(df1['phone'][i])<10:
            df1['phone'][i]='0'
       
    return df1
filtered_cvs=fix_value(df1)

C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['phone'][i]='0'
C:\Users\Sravani\AppData\Local\Temp\ipykernel_15276\3672717264.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:


In [134]:
filtered_cvs.to_csv('filtered_csv.csv',index=False)

In [136]:
df1['amount'].fillna(df1['amount'].mean())
df1

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location,countrycode
0,1,Michelle Kidd,vayala@example.net,6197234258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8,2652.57,2025-04-19 14:46:00,Home,Credit Card,New York,AE
1,4,Kimberly Price,jessicaknight@example.com,4232229779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427,1787.09,2025-04-28 04:34:07,Beauty,PayPal,Chicago,CA
2,5,Matthew Phillips,qwilliams@example.com,2207633522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452,1983.52,2025-02-03 14:59:13,Sports,PayPal,Online,OR
3,7,Louis Miller,patriciaelliott@example.org,1988627105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,470,3241.66,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles,CT
4,7,Louis Miller,patriciaelliott@example.org,1988627105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,857,697.57,2025-06-13 12:03:42,Beauty,Debit Card,Chicago,CT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Deanna Johnson,ycook@example.org,5763204824,"601 Contreras Forges, Michaelfurt, KY 30733",01-11-2023,Silver,532,759.38,2025-03-14 16:56:22,Home,PayPal,New York,KY
996,995,Deanna Johnson,ycook@example.org,5763204824,"601 Contreras Forges, Michaelfurt, KY 30733",01-11-2023,Silver,617,821.18,2025-01-23 07:39:19,Electronics,Debit Card,Miami,KY
997,997,Jodi Simpson,eric24@example.org,4836252940,"2876 Tucker Road Suite 947, North Tommyborough...",18-04-2024,Bronze,45,480.64,2025-01-06 08:27:59,Home,Credit Card,Los Angeles,AL
998,998,Crystal Brown,pshaffer@example.net,3907473088,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",30-08-2024,Bronze,304,73.71,2025-01-27 05:33:22,Home,Debit Card,Chicago,DE
999,998,Crystal Brown,pshaffer@example.net,3907473088,"095 Janice Forest Suite 570, Boltonmouth, DE 7...",30-08-2024,Bronze,886,NaN,2025-03-16 15:42:17,Beauty,Debit Card,Online,DE